version: '3.3'

services:
  v-core:
    hostname: v-core
    build: ./
    volumes:
      - ./src:/usr/src/app/src:ro
    environment:
      - ES_PROTOCOL=http
      - ES_HOST=elastic_01
      - ES_PORT=9200
    ports:
      - "5000:5000"
    networks:
      - v-network
    depends_on: ["elastic_01"]

  elastic_01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elastic_01
    environment:
      - node.name=elastic_01
      - cluster.name=es-cluster
      - discovery.seed_hosts=elastic_02,elastic_03
      - cluster.initial_master_nodes=elastic_01,elastic_02,elastic_03
      - path.repo=/usr/share/elasticsearch/backup
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic/data/node-1:/usr/share/elasticsearch/data
      - ./elastic/data/backup:/usr/share/elasticsearch/backup
    healthcheck:
      test: curl http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 9200:9200
    networks:
      - v-network

  elastic_02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elastic_02
    environment:
      - node.name=elastic_02
      - cluster.name=es-cluster
      - discovery.seed_hosts=elastic_01,elastic_03
      - cluster.initial_master_nodes=elastic_01,elastic_02,elastic_03
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backup
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic/data/node-2:/usr/share/elasticsearch/data
      - ./elastic/data/backup:/usr/share/elasticsearch/backup
    networks:
      - v-network

  elastic_03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elastic_03
    environment:
      - node.name=elastic_03
      - cluster.name=es-cluster
      - discovery.seed_hosts=elastic_01,elastic_02
      - cluster.initial_master_nodes=elastic_01,elastic_02,elastic_03
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backup
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic/data/node-3:/usr/share/elasticsearch/data
      - ./elastic/data/backup:/usr/share/elasticsearch/backup
    networks:
      - v-network

  wait_until_ready:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    command: /usr/bin/true
    depends_on: ['elastic_01']
    networks:
      - v-network

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.9.1"
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      SERVERNAME: localhost
      ELASTICSEARCH_URL: http://elastic_01:9200
      ELASTICSEARCH_HOSTS: http://elastic_01:9200
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: Superdf@1
    networks:
      - v-network
    depends_on: ['elastic_01']

networks:
  v-network: 
    driver: bridge

volumes:
  elastic_data_01:
    driver: local
  elastic_data_02:
    driver: local
  elastic_data_03:
    driver: local